# blank line on the top
add_newline = true

format = """$env_var $username [-](green) $hostname [-](green) $directory $all"""
# format = """
# [â•­â•´](grey)$username \
# $hostname \
# $directory \
# $all \
# \n[â•°â”€](grey)$character"""

[character]
success_symbol = "[ =>](bold green)"
# success_symbol = ""
error_symbol = "[ =>](bold red)"

[env_var.STARSHIP_DISTRO]
format = "[$env_value](white)"
variable = "STARSHIP_DISTRO"
disabled = false

[username]
style_user = "white"
style_root = "red"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[$hostname](bold yellow)"
disabled = false

[directory]
# truncation_length = 5
# truncation_symbol = ".../"
home_symbol = "ïŸ ~"
read_only_style = "197"
read_only = " ï€£ "
format = "[$path]($style)[$read_only]($read_only_Style)"

[git_branch]
symbol = "î‚  "
format = "[-](green) [$symbol$branch]($style) "
truncation_symbol = ".../"
style = "bold green"

[git_status]
format = '[-](green) [\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "ğŸ³"
up_to_date = "ï† "
untracked = "ï”© "
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
stashed = "ï£– "
modified = "ï„ "
staged = '[++\($count\)](green)'
renamed = "ïª¶ "
deleted = "ï€” "

[docker_context]
format = "[-](green) [ïŒˆ $context](bold blue) "
disabled = true

[python]
symbol = "ï Ÿ "
python_binary = "python3"
disabled = true

[nodejs]
format = "[-](green) [ï¢˜ $version](bold green) "
disabled = true
